<script id="config-script">
	var userId = <?php echo $application->userId ?>;
	var userProfile = <?php echo json_encode( $application->userProfile ) ?>;
	var childId = 0;
	var childProfile = {};
	var language = '<?php echo getLanguage() ?>';
	
	var baseUrl = '<?php echo BASE_URL ?>';
	var ajaxUrl = '<?php echo AJAX_URL ?>';
	
	var texts = {
		entryAdded: '<?php echo __('Entry added') ?>',
		entryRemoved: '<?php echo __('Entry removed') ?>',
		entrySaved: '<?php echo __('Entry saved') ?>',
		atLeastOneOfThisFieldsIsRequired: '<?php echo __('At least one of this fields is required') ?>',
		youMustSelectAOption: '<?php echo __('You must select a option') ?>',
		areYouSureYouWantToDeleteThisEntry: '<?php echo __('Are you sure you want to delete this entry') ?>',
		youNeedToSignInFirst: '<?php echo __('You need to sign in first') ?>',
		close: '<?php echo __('Close') ?>',
		prev: '<?php echo __('Prev') ?>',
		next: '<?php echo __('Next') ?>',
		current: '<?php echo __('Current') ?>',
		january: '<?php echo __('January') ?>',
		february: '<?php echo __('February') ?>',
		march: '<?php echo __('March') ?>',
		april: '<?php echo __('April') ?>',
		may: '<?php echo __('May') ?>',
		june: '<?php echo __('June') ?>',
		july: '<?php echo __('July') ?>',
		august: '<?php echo __('August') ?>',
		september: '<?php echo __('September') ?>',
		october: '<?php echo __('October') ?>',
		november: '<?php echo __('November') ?>',
		december: '<?php echo __('December') ?>',
		jan: '<?php echo __('Jan') ?>',
		feb: '<?php echo __('Feb') ?>',
		mar: '<?php echo __('Mar') ?>',
		apr: '<?php echo __('Apr') ?>',
		may: '<?php echo __('May') ?>',
		jun: '<?php echo __('Jun') ?>',
		jul: '<?php echo __('Jul') ?>',
		aug: '<?php echo __('Aug') ?>',
		sep: '<?php echo __('Sep') ?>',
		oct: '<?php echo __('Oct') ?>',
		nov: '<?php echo __('Nov') ?>',
		dec: '<?php echo __('Dec') ?>',
		monday: '<?php echo __('Monday') ?>',
		tuesday: '<?php echo __('Tuesday') ?>',
		wednesday: '<?php echo __('Wednesday') ?>',
		thursday: '<?php echo __('Thursday') ?>',
		friday: '<?php echo __('Friday') ?>',
		saturday: '<?php echo __('Saturday') ?>',
		sunday: '<?php echo __('Sunday') ?>',
		mon: '<?php echo __('Mon') ?>',
		tue: '<?php echo __('Tue') ?>',
		wed: '<?php echo __('Wed') ?>',
		thu: '<?php echo __('Thu') ?>',
		fri: '<?php echo __('Fri') ?>',
		sat: '<?php echo __('Sat') ?>',
		sun: '<?php echo __('Sun') ?>',
		mo: '<?php echo __('Mo') ?>',
		tu: '<?php echo __('Tu') ?>',
		we: '<?php echo __('We') ?>',
		th: '<?php echo __('Th') ?>',
		fr: '<?php echo __('Fr') ?>',
		sa: '<?php echo __('Sa') ?>',
		su: '<?php echo __('Su') ?>',
		chooseATime: '<?php echo __('Choose a time') ?>',
		time: '<?php echo __('Time') ?>',
		hour: '<?php echo __('Hour') ?>',
		minute: '<?php echo __('Minute') ?>',
		second: '<?php echo __('Second') ?>',
		millisec: '<?php echo __('Millisec') ?>',
		timezone: '<?php echo __('Timezone') ?>',
		thisEmailAlreadyExistsInOurDatabase: '<?php echo __('This email already exists in our database') ?>',
		areYouSureYouWantToDeleteThisChild: '<?php echo __('Are you sure you want to delete this child') ?>',
		childSaved: '<?php echo __('Child saved') ?>',
		childRemoved: '<?php echo __('Child removed') ?>',
	};
</script>